### ISSUE TITLE
Moving to net.kyori.adventure.text.component

### ISSUE THREAD

**Issue by VanyaNexus** [Janmm14/JsonMessageMaker#2]
Are there any plans to switch to net.kyori.adventure.text.component as the BaseComponent object is deprecated in the new versions of Paper 1.19?

**Comment by Janmm14** [comment]
Just because paper deprecates stuff doesn't mean it'd ever vanish because of spigot compat.

I don't remember atm, but if I would add overloads or so with kyori components, would it still load under spigot?

If yes, I can add such overloads which would hide the dirty conversion to BaseComponents.
If somene is willing to provide a "native" implementation using kyori components, I'd happily accept such a PR.
(as long as its not removing the existing basecomponent implementation)

Also I am not sure whether this plugin would be useful at all, since kyori already has an alternative, html-like string conversion method. - when you are using kyori already in your plugin, you either have the libs for spigot shaded or are already locking the plugin to paper, so i would suggest to use kyori's system in such cases and not this one.

**Comment by VanyaNexus** [comment]
ok i got it, thanks for the reply
